language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - gatsby build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: ffmemes.com
  local_dir: public
  on:
    branch: master
